#!/bin/sh
set -e

echo "Setting conf"

if [ ! -e /config/aria2.session ]
then
  touch /config/aria2.session
fi

if [ ! -e /config/aria2.conf ]
then
  cp /aria2.conf.default /config/aria2.conf
fi

echo "[DONE]"

echo "Setting owner and permissions"

chown -R dummy:dummy /config
find /config -type d -exec chmod 755 {} +
find /config -type f -exec chmod 644 {} +

echo "[DONE]"

echo "Starting aria2c"

exec /usr/local/bin/goreman start

echo 'Exiting aria2'
